package com.example.myapplication.mainScreen;

import android.Manifest;
import android.content.pm.PackageManager;
import android.util.Log;
import android.view.MotionEvent;
import android.view.View;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;
import androidx.core.content.ContextCompat;

import com.example.myapplication.R;
import com.example.myapplication.database.MovementActivity;
import com.example.myapplication.database.StillLocation;
import com.example.myapplication.database.TimelineItem;
import com.google.android.gms.maps.CameraUpdateFactory;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.OnMapReadyCallback;
import com.google.android.gms.maps.SupportMapFragment;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.LatLngBounds;
import com.google.android.gms.maps.model.MarkerOptions;

public class MapManager implements OnMapReadyCallback {
    private static final String TAG = "MapManager";
    private final Fragment fragment;
    private final int fragmentId;
    private GoogleMap mMap;
    private View mapFragmentView;

    public MapManager(Fragment fragment, int fragmentId) {
        this.fragment = fragment;
        this.fragmentId = fragmentId;
    }

    public void init() {
        mapFragmentView = fragment.requireView().findViewById(fragmentId);
        SupportMapFragment mapFragment = (SupportMapFragment) fragment.getChildFragmentManager()
                .findFragmentById(fragmentId);
        if (mapFragment != null) {
            mapFragment.getMapAsync(this); //calling the map
        }

        View touchOverlay = fragment.requireView().findViewById(R.id.map_touch_overlay);

        if (touchOverlay != null) { // Set a touch listener if there is no overlay
            touchOverlay.setOnTouchListener((v, event) -> {
                //generated by Gemini
                if (v.getParent() != null) {
                    switch (event.getAction()) {
                        case MotionEvent.ACTION_DOWN:
                            // Disallow parent views to intercept touch events immediately
                            v.getParent().requestDisallowInterceptTouchEvent(true);
                            break;
                        case MotionEvent.ACTION_UP:
                        case MotionEvent.ACTION_CANCEL:
                            // Allow parent views to intercept again
                            v.getParent().requestDisallowInterceptTouchEvent(false);
                            break;
                    }
                }
                // Return false so the touch event still reaches the map underneath
                return false;
            });
        }
    }

    @Override
    public void onMapReady(@NonNull GoogleMap googleMap) {
        mMap = googleMap;

        mMap.getUiSettings().setAllGesturesEnabled(true);
        mMap.getUiSettings().setZoomControlsEnabled(true);
        mMap.getUiSettings().setScrollGesturesEnabled(true);
        mMap.getUiSettings().setZoomGesturesEnabled(true);
        mMap.getUiSettings().setTiltGesturesEnabled(true);
        mMap.getUiSettings().setRotateGesturesEnabled(true);
        
        updateMyLocationEnabled();
    }

    public void onResume() {
        updateMyLocationEnabled();
    }

    public void setVisibility(int visibility) {
        if (mapFragmentView != null) {
            mapFragmentView.setVisibility(visibility);
        }
        View touchOverlay = fragment.requireView().findViewById(R.id.map_touch_overlay);
        if (touchOverlay != null) {
            touchOverlay.setVisibility(visibility);
        }
    }

    /**
     * Focuses the map on a specific timeline item (Still or Movement).
     * Clears previous markers and animates the camera to the new location(s).
     */
    public void focusOnItem(TimelineItem item) {
        if (mMap == null) return;

        // Clear existing markers
        mMap.clear();

        if (item instanceof StillLocation) {
            // Handle still locations, add a single marker and zoom in
            StillLocation still = (StillLocation) item;
            if (still.lat != null && still.lng != null) {
                LatLng pos = new LatLng(still.lat, still.lng);
                mMap.addMarker(new MarkerOptions().position(pos).title("Still Location"));
                mMap.animateCamera(CameraUpdateFactory.newLatLngZoom(pos, 15f));
            }
        } else if (item instanceof MovementActivity) {
            // Handle movement activities, add start and end markers and fit both in view
            MovementActivity movement = (MovementActivity) item;
            LatLngBounds.Builder builder = new LatLngBounds.Builder();
            boolean hasPoints = false;

            // Add marker for start position
            if (movement.startLat != null && movement.startLng != null) {
                LatLng start = new LatLng(movement.startLat, movement.startLng);
                mMap.addMarker(new MarkerOptions().position(start).title("Start"));
                builder.include(start);
                hasPoints = true;
            }
            // Add marker for end position=
            if (movement.endLat != null && movement.endLng != null) {
                LatLng end = new LatLng(movement.endLat, movement.endLng);
                mMap.addMarker(new MarkerOptions().position(end).title("End"));
                builder.include(end);
                hasPoints = true;
            }

            if (hasPoints) {
                try {
                    // Fit the camera to include both markers
                    mMap.animateCamera(CameraUpdateFactory.newLatLngBounds(builder.build(), 100));
                } catch (IllegalStateException e) {
                    // Fallback: If bounds can't be built (e.g., view not ready or single point), zoom to start TODO CHANGE TO CURRENT POSTION
                    if (movement.startLat != null) {
                        mMap.animateCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(movement.startLat, movement.startLng), 15f));
                    }
                }
            }
        }
    }

    private void updateMyLocationEnabled() {
        // code taken from google
        if (mMap != null && ContextCompat.checkSelfPermission(fragment.requireContext(), Manifest.permission.ACCESS_FINE_LOCATION)
                == PackageManager.PERMISSION_GRANTED) {
            try {
                mMap.setMyLocationEnabled(true);
            } catch (SecurityException e) {
                Log.e(TAG, "SecurityException setting my location enabled", e);
            }
        }
    }
}
