name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Inject API Key
      run: |
        echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > secrets.properties
        echo "MAPS_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> secrets.properties
        cp secrets.properties app/secrets.properties
        cp secrets.properties local.defaults.properties
        cp secrets.properties app/local.defaults.properties
        
    - name: Debug API Key
      env:
        SECRET_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        echo "1. Checking if the secret is empty..."
        if [ -z "$SECRET_KEY" ]; then echo "SECRET IS EMPTY!"; else echo "Secret has a value."; fi
        
        echo "2. Printing character length..."
        echo "Length: ${#SECRET_KEY}"
        
        echo "3. Printing the raw key (spaced out to bypass mask)..."
        echo "$SECRET_KEY" | sed 's/./& /g'


    - name: Build with Gradle
      run: ./gradlew clean assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/**/*.apk
